# Copyright 2024 - Andrew Kwok Fai LUI, Robotics and Autonomous System Group,
# Research Engineering Facility, RI
# the Queensland University of Technology

services:
    cgras_image:
        build:
            context: .
            dockerfile: Dockerfile
        image: cgras_image
        container_name: cgras_image
        devices:
            - /dev/dri
        group_add:
            - video
        stdin_open: true
        tty: true
        privileged: true
        environment:
            - DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_MASTER=true
            - ROS_MASTER_URI=http://localhost:11311
            # - ROS_MASTER_URI=http://192.168.1.50:11311
            # - ROS_IP=192.168.1.50
        network_mode:  host
        # ipc: host
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ~/.ssh:/home/qcr/.ssh  
            # - ~/cgras_ws/src/cgras_messages:/home/qcr/cgras_ws/src/cgras_messages:rw     
            - ~/cgras_ws/src/cgras_detector:/home/qcr/cgras_ws/src/cgras_detector:rw   
            # - ~/cgras_ws/src/cgras_coordinator:/home/qcr/cgras_ws/src/cgras_coordinator:rw 
            - ~/cgras_ws/src/cgras_datatools:/home/qcr/cgras_ws/src/cgras_datatools:rw                      
            - ~/cgras_data:/home/qcr/cgras_data:rw
   
        # networks:
        #     app_net:
        #         ipv4_address: 192.168.1.60 
        command:
            bash
         