# YAML file for the system
---
cgras_detector:
  web_host: 0.0.0.0
  web_port: 8023
  web_debug_mode: True
  web_debug_hot_reload: False
  # auxillary web server
  aux_web_host: 0.0.0.0
  aux_web_port: 8024
  aux_web_directory: /home/qcr/cgras_data/detector/data
  # automation mode (whether the task execution is automated)
  task_automation: False  
  # default ros topics
  ros_coordinator_state_topic: '/cgras/coordinator/state' 
  ros_detector_state_topic: '/cgras/detector/state' 
  # timers for driving the system and refresh the GUI
  system_timer: 1  # seconds
  dashboard_timer: 1  # seconds
  # the data folder
  cgras_data_folder: /home/qcr/cgras_data
  # connection timeout
  connection_timeout: 120   # seconds
  # yolo model range
  max_coral_age: 120  # days
  # ----
  # detection task parameters
  task_params_filename: params.yaml
  reco_model_filename: reco_model.yaml
  loctile_model_filename: loctile_model.yaml
  reco_working_scale: 0.1
  reco_debug_images_at_original_scale: False
  reco_debug_feature_matching_images: True
  reco_feature_detector: brisk               # sift, orb, brisk, akaze
  reco_feature_matching_confidence_threshold: 1.0
  reco_image_matching_min_confidence: 0.6
  reco_image2d_matching_min_confidence: 0.6
  cod_model_filename: coral_object_detect_model.yaml 
  cod_debug_blob_images: True
  cod_blob_overlap_pix: 128
  cod_use_cached_object_detection: True
  cod_duplicate_max_displacement_images: 32
  cod_duplicate_max_displacement_blobs: 32 